### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by kaizirlewagen** [Arul-/reactive-restler#2]
You send me the new ro link from 
https://github.com/Luracast/Restler/issues/645#issuecomment-756261999

i try to test the new version, but after git clone i got the following errors ...
```
PHP Warning:  include(/var/www/html/reactive-restler/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/reactive-restler/api/bootstrap.php on line 25, referer: http://127.0.0.1/reactive-restler/
PHP Warning:  include(): Failed opening '/var/www/html/reactive-restler/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/reactive-restler/api/bootstrap.php on line 25, referer: http://127.0.0.1/reactive-restler/
PHP Fatal error:  Uncaught Error: Class 'Luracast\\Restler\\Defaults' not found in /var/www/html/reactive-restler/api/bootstrap.php:27\nStack trace:\n#0 /var/www/html/reactive-restler/public/index.php(5): require()\n#1 /var/www/html/reactive-restler/server.php(10): include('/var/www/html/r...')\n#2 {main}\n  thrown in /var/www/html/reactive-restler/api/bootstrap.php on line 27, referer: http://127.0.0.1/reactive-restler/
```
Is something missing in the repo?

**Comment by Arul-** [comment]
If you just cloned this repo you need to run `composer install`

Otherwise, you can call `composer create-project arul/reactphp-restler my-project` to do both steps in one.

I recommend https://github.com/Arul-/RestlerApplication for a test drive. Just follow the readme

**Comment by Arul-** [comment]
With this repo, you can run `composer serve` to run the examples in PHP development server

**Comment by kaizirlewagen** [comment]
Thx for your help. Works like expected. I will check it out.
